/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mycalculator;

import javax.swing.JOptionPane;

/**
 *
 * @author Stepin2
 */
public class CalculatorForm extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorForm
     */
    public CalculatorForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mPlusButton = new javax.swing.JButton();
        mMinusButton = new javax.swing.JButton();
        mMultiplyButton = new javax.swing.JButton();
        mDivideButton = new javax.swing.JButton();
        mFirstNumber = new javax.swing.JTextField();
        mSecondNumber = new javax.swing.JTextField();
        mAnswerLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mPlusButton.setText("+");
        mPlusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPlusButtonActionPerformed(evt);
            }
        });

        mMinusButton.setText("-");
        mMinusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMinusButtonActionPerformed(evt);
            }
        });

        mMultiplyButton.setText("*");
        mMultiplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMultiplyButtonActionPerformed(evt);
            }
        });

        mDivideButton.setText("/");
        mDivideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mDivideButtonActionPerformed(evt);
            }
        });

        mFirstNumber.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        mFirstNumber.setToolTipText("First Number");

        mSecondNumber.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        mSecondNumber.setToolTipText("Second Number");

        mAnswerLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mAnswerLabel.setText("The answer is");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MyCalculator created by StepIn2It");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mSecondNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(mFirstNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mAnswerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(mPlusButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(mMinusButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(mMultiplyButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(mDivideButton))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(mFirstNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(mSecondNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mPlusButton)
                    .addComponent(mMinusButton)
                    .addComponent(mMultiplyButton)
                    .addComponent(mDivideButton))
                .addGap(35, 35, 35)
                .addComponent(mAnswerLabel)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mPlusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPlusButtonActionPerformed
        // TODO add your handling code here:
        int a = 0;
        int b = 0;
        try
        {
           a = Integer.parseInt(this.mFirstNumber.getText());
           b = Integer.parseInt(this.mSecondNumber.getText());
        } 
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "The values you input are incorrect", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        int c = a + b;
        this.mAnswerLabel.setText("The answer is " + c);
    }//GEN-LAST:event_mPlusButtonActionPerformed

    private void mMinusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mMinusButtonActionPerformed
        // TODO add your handling code here:
        int a = 0;
        int b = 0;
        try
        {
           a = Integer.parseInt(this.mFirstNumber.getText());
           b = Integer.parseInt(this.mSecondNumber.getText());
        } 
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "The values you input are incorrect", "Error", JOptionPane.ERROR_MESSAGE);
        }
        int c = a-b;
        this.mAnswerLabel.setText("The answer is " + c);
    }//GEN-LAST:event_mMinusButtonActionPerformed

    private void mMultiplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mMultiplyButtonActionPerformed
        // TODO add your handling code here:
        int a = 0;
        int b = 0;
        try
        {
           a = Integer.parseInt(this.mFirstNumber.getText());
           b = Integer.parseInt(this.mSecondNumber.getText());
        } 
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "The values you input are incorrect", "Error", JOptionPane.ERROR_MESSAGE);
        }
        int c = a * b;
        this.mAnswerLabel.setText("The answer is " + c);
    }//GEN-LAST:event_mMultiplyButtonActionPerformed

    private void mDivideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mDivideButtonActionPerformed
        // TODO add your handling code here:
        int a = 0;
        int b = 0;
        int c = 0;
        try
        {
            a = Integer.parseInt(this.mFirstNumber.getText());
            b = Integer.parseInt(this.mSecondNumber.getText());
            c = a / b;
        } 
        catch (Exception e)
        {
           
            JOptionPane.showMessageDialog(this, e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
      
        this.mAnswerLabel.setText("The answer is " + c);
    }//GEN-LAST:event_mDivideButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel mAnswerLabel;
    private javax.swing.JButton mDivideButton;
    private javax.swing.JTextField mFirstNumber;
    private javax.swing.JButton mMinusButton;
    private javax.swing.JButton mMultiplyButton;
    private javax.swing.JButton mPlusButton;
    private javax.swing.JTextField mSecondNumber;
    // End of variables declaration//GEN-END:variables
}
